---
  title: "R sectio nationality analysis"
author: "Adam Finnemann"
date: "September 24, 2017"
---

Isn't finished. 
  
```{r setup, include=FALSE}

library(pacman)
p_load("stringr","ggplot2","ggExtra","lmerTest","tidyverse", "zoo","lubridate", "data.table")

setwd("~/Historie projekt/historie project/LONSEA_DB/spring18/nationalities_all")
da <- read.csv(list.files(pattern = "contract_"))
```

loading data
```{r}


important_workers = da %>% 
  filter(str_detect(da$fname, "Section") | str_detect(da$fname, "Director") | str_detect(da$fname, "Chief") | str_detect(da$fname, "Expert"),
         fname != "Secretary of Section")

section_worker <- important_worker %>% 
  mutate( nationality = recode(nationality, "English" = "British"))
```



forming nationality/employment data frame
```{r}


mdl_df <- section_worker %>% 
  select(pname, fname_code,begin_date, end_date) %>% 
  mutate(begin_date = as.Date(begin_date),
         end_date = as.Date(end_date))

result <- setDT(mdl_df)[
  .(mseq = seq(as.Date("1919-01-01"), as.Date("1948-12-30"), by = "1 year")), 
  on = .(begin_date <= mseq, end_date >= mseq), nomatch = 0L, allow.cartesian = TRUE][
    , dcast(unique(.SD), pname ~ end_date, toString, value.var = "fname_code")]

result_nats <- merge(result, section_worker[,c(8,20)], by = "pname")

result_nats <- result_nats[,-1]


#A MIRACLE!!!
nation_workers <- result_nats %>% 
  group_by(nationality) %>% 
  summarise_all(function(x) sum(x != ""))

long_df <- gather(nation_workers, key, value, `1920-01-01`:`1947-01-01`) %>% 
  mutate(key = as.Date(key)) 





long_df %>% 
  filter(value > 10) %>% 
  ggplot(aes(x = key, y = value, fill = nationality, color = nationality)) +
  geom_col() +
  scale_x_date(date_breaks = "3 year", date_labels = "%Y") +
  labs(x = "Year", y ="Workers", titles = "Nations with +10 Workers in Section")

#function for plotting

plot_section_workers <- function(df, minimum_worker = 5){
  df %>% 
    filter(value > minimum_worker) %>% 
    ggplot(aes(x = key, y = value, fill = nationality, color = nationality)) +
    geom_col() +
    scale_x_date(date_breaks = "2 year", date_labels = "%Y") +
    labs(x = "Year", y ="Workers", titles = paste("Nations with", minimum_worker,"+ Workers in Section"))
}


```


```{r}
plot_section_workers(long_df, 15)

```

```{r}
plot_section_workers(long_df, 10)

```

```{r}
plot_section_workers(long_df, 8)

```

```{r}
plot_section_workers(long_df, 7)

```
