---
  title: "R markdown template""
author: "Adam Finnemann"
date: "September 24, 2017"
---

```{r setup, include=FALSE}

library(pacman)
p_load("stringr","ggplot2","ggExtra","lmerTest","tidyverse", "zoo","lubridate", "data.table")


setwd("~/Historie projekt/historie project/LONSEA_DB/data")
#setwd("~/Historie projekt/historie project/LONSEA_DB")
da <- read.csv("lon_data_w_GA.csv")

```



Correcting nationalities of directors, and aligning namings:
```{r}

#Nationalities assignments for Directors
indx <- da$pname == "Dr. Jur. Thanassis (Athanase) Aghnides"
da[indx,15] <- "Greek"

indx <- da$pname == "Erik Andreas Colban"
da[indx,15] <- "Norwegian"


indx <- da$pname == "Juan Antonio Buero"
da[indx,15] <- "Uruguayan"

indx<- da$pname == "Yotaro Sugimura"
da$nationality <- as.character(da$nationality)
da[indx,15] <- "Japanese"


indx <- da$pname == "Prof. Inazo Nitobé"
da[indx,3] <- "Inazo Nitobe"
da[indx,4] <- 0
da[indx,15] <- "Japanese"
indx <- da$pname == "Inazo Nitobe"
da[indx,15] <- "Japanese"
da[indx,8] <- 1862

indx <- da$pname == "Hans Christian Berg"
da[indx,15] <- "Norwegian"

indx <- da$pname == "Francis Yeats-Brown"
da[indx,12]  = 1927

indx <- da$pname == "Oscar Uno Konrad Thorsing"
da[indx,9]  = 1924
da[indx,12]  = 1925

indx <- da$pname == "Paul Gilles Léon Deperon"
da[indx,15]  = "Belgian"


indx <- da$pname == "Hideo Masutani"
da[indx,15]  = "Japanese"

indx <- da$pname == "Yotaro Sugimura"
da[indx,15]  = "Japanese"

#Correcting spelling mistake (Kaechkenheeck -> h to b)
indx <- da$pname == "Georges Silvain François Charles Kaeckenheeck"
da[indx,3]  = "Georges Silvain François Charles Kaeckenbeeck"
indx <- da$pname == "Georges Silvain François Charles Kaeckenbeeck"
da[indx,15]  = "Belgian"


#aligning names of Morikatsu Inagaki
indx <- da$pname == "Mr. Morikatsu Imagaki"
da[indx,3]  = "Morikatsu Inagaki"
indx <- da$pname == "Morikatsu Inagaki"
da[indx,15]  = "Japanese"
#Removing assistant contract which isn't in original databse. See Torsten mail 1/02/2018
#Two of his contracts are doubled, one coded as beloning it "political" section, the other to "Under Secretaries-Generals' in charge of Political Section Office". Only poltiical section is kept
da = da %>%
  filter(!(canonical_fname == "Second Division" & pname == "Morikatsu Inagaki"),
         !(oname == "Under Secretaries-Generals' in charge of Political Section Office" & pname == "Morikatsu Inagaki"))
#Four contracts remain, this is in agreement with the archieve. 



#Louis Variez is removed. This is a duplicate with mispelled name of the contract of L. Varlez.

da = da %>% 
  filter(pname != "Louis Variez")


indx <- da$pname == "Frédéric Blondeel"
da[indx,15]  = "Belgian"


indx <- da$pname == "Dr. Tsune Ouchi"
da[indx,15]  = "Japanese"

indx <- da$pname == "Stanislawa Adamowicz"
da[indx,15]  = "Polish"

indx <- da$pname == "Dr. Shoji Kanai"
da[indx,15]  = "Japanese"

indx <- da$pname == "Dr. Genzo Katoh"
da[indx,15]  = "Japanese"

indx <- da$pname == "Dr. Tôyôjirô Kitano"
da[indx,15]  = "Japanese"

indx <- da$pname == "Dr. Hiroshi Kusama"
da[indx,15]  = "Japanese"

indx <- da$pname == "Shiko Kusama"
da[indx,15]  = "Japanese"

indx <- da$pname == "Juan Antonio Buero"
da[indx,15]  = "Uruguayan"


indx <- da$pname == "Kinjiro Mori"
da[indx,15]  = "Japanese"


indx <- da$pname == "Tetsuro Furukaki"
da[indx,15]  = "Japanese"


indx <- da$pname == "Ross Tolmie"
da$fname = as.character(da$fname)
da[indx,5]  = "Temporary Collaborator"


indx <- da$pname == "Dr. Hector Rulot"
da[indx,15]  = "Belgian"
da[indx,8]  = 1877


indx <- da$pname == "Ida Spellman"
da[indx,15]  = "Belgian"

indx <- da$pname == "Anna Teresa Paradas"
da[indx,15]  = "Colombian"

indx <- da$pname == "Adrianus Pelt"
da[indx,8]  = 1982

#adding director in information section contract for Pelt
c = c(000, 000, "Adrianus Pelt", 0, "Director", "First Division", "Information Section", 1982, 1934,1,1,1940,12,31,"Belgian")

da = rbind(da, c)

#Natioanlity set to belgian
indx <- da$pname == "Adrianus Pelt"
da[indx,15]  = "Belgian"



indx <- da$pname == "Fernando Maria Castiella"
da[indx,15]  = "Chilean"


#41) William Rappard
#has no birth year: it is 1883 (source his personnel file)

indx <- da$pname == "Prof. William E. Rappard"
da[indx,8]  = 1883


#42) Walter Layton
#has no birth year: it is 1884 (source his personnel file)
#has no first name: Walter 

indx <- da$pname == "W. Layton"
da[indx,8]  = 1884





```


Aligning nationalities asignments:

```{r}
da$nationality <- str_replace_all(da$nationality,", Swiss", "Swiss")
da$nationality <- str_replace_all(da$nationality,"BritishSwiss", "British, Swiss")
da$nationality <- str_replace_all(da$nationality,"English, Dane English,", "English, Dane")
da$nationality <- str_replace_all(da$nationality,"Fench  French,", "French")
da$nationality <- str_replace_all(da$nationality,"French,French", "French")
da$nationality <- str_replace_all(da$nationality,"LatvianSwiss", "Latvian, Swiss")
da$nationality <- str_replace_all(da$nationality,"AlbanianSwiss", "Albanian, Swiss")
da$nationality <- str_replace_all(da$nationality,"Dane, Dane", "Dane")
da$nationality <- str_replace_all(da$nationality,"Dane,Dane", "Dane")
da$nationality <- str_replace_all(da$nationality,"French, BritishSwiss", "French, British, Swiss")
da$nationality <- str_replace_all(da$nationality,"SwissSwiss", "Swiss")
da$nationality <- str_replace_all(da$nationality,"British, British", "British")
da$nationality <- str_replace_all(da$nationality,"French, French", "French")
da$nationality <- str_replace_all(da$nationality,"ItalianSwiss", "Italian, Swiss")
da$nationality <- str_replace_all(da$nationality,"SwissSwissSwiss", "Swiss")
da$nationality <- str_replace_all(da$nationality,"RussianSwiss", "Russian, Swiss")
da$nationality <- str_replace_all(da$nationality,"Italian, Italian", "Italian")
da$nationality <- str_replace_all(da$nationality,"DutchSwiss", "Dutch, Swiss")
da$nationality <- str_replace_all(da$nationality,"SwissSwiss", "Swiss")
da$nationality <- str_replace_all(da$nationality,"Swiss,Swiss", "Swiss")
da$nationality <- str_replace_all(da$nationality,"FrenchSwiss", "French, Swiss")
da$nationality <- str_replace_all(da$nationality,",Swiss", "Swiss")
da$nationality <- str_replace_all(da$nationality,"British,British", "British")
da$nationality <- str_replace_all(da$nationality,"Italian,Italian", "Italian")
da$nationality <- str_replace_all(da$nationality,"Austrian,Austrian", "Austrian")
da$nationality <- str_replace_all(da$nationality,"Greek,Greek", "Greek")
#Aligning British and English personnel
da$nationality <- str_replace_all(da$nationality,"British", "English")



da <- da %>% 
mutate(nationality = as.factor(nationality))

summary(da$nationality)
```


Adding ordinal fnames scale
```{r}
# import data frame of rank names to ordinal scale
setwd("~/Historie projekt/historie project/LONSEA_DB")
ordinal_ranks <- read.csv("data/fname_u_with_class.csv", sep = ",", header = FALSE, stringsAsFactors = FALSE)# changed original category csv due to encoding
# column names
colnames(ordinal_ranks) = c("u_id", "u_fname" , "u_fname_code")
# code every object in main
extract_rank <- rep(NA,nrow(da))


for(i in 1:nrow(ordinal_ranks)){
  #for each rank a logical vector indexing subject numbers are created
  idx <- ordinal_ranks$u_fname[i] == da$fname
  #true index are translated to oridnal rank numbers for each subject
  extract_rank[idx] <- ordinal_ranks$u_fname_code[i]
}
#ordinal rank numbers are added and code is reversed, so that 9 = highest (directors etc) rank, and 1 = lowest (cleaners etc)

da <- da %>% 
  mutate(fname_code = extract_rank,
         fname_code = 10 - fname_code)



```


Filtering out based on missing data

```{r}
subset <- da %>%
  filter(begin_on_year > 1900 & end_on_year > 1915, begin_on_year < end_on_year)

missing <- da %>%
  filter(begin_on_year < 1900 | is.na(begin_on_year) | is.na(end_on_year) | end_on_year < 1915 |begin_on_year > end_on_year)


summary(subset$nationality)
```


```{r}
write.csv(subset, "lon_data_w_GA.csv", row.names = F)
write.csv(missing, "missing_begin_on_year.csv", row.names = F)

```

```{r}
top_missing = 
  missing %>% 
  filter(str_detect(missing$fname, "Section") | str_detect(missing$fname, "Director") | str_detect(missing$fname, "Chief") | str_detect(missing$fname, "Expert"),
         fname != "Secretary of Section")

missing_higher_officials <- missing %>% 
  filter(str_detect(missing$fname, "Section")| #including "Section"
         str_detect(missing$fname, "Director")| #Including Directors
         str_detect(missing$fname, "Chief") | #Including Chief
         str_detect(missing$fname, "Expert")|
         str_detect(missing$fname, "Head"), #Including Expert
         fname != "Secretary of Section",
         canonical_fname != "Second Division",
         canonical_fname != "Third Division") #Excluding Secretary

write.csv(missing, "missing_higher_officials.csv", row.names = F)
```

